const posts = [
  {
    id: 1,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 2,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 3,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 4,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 5,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 6,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 7,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 8,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 9,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 10,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 11,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 12,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 13,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 14,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 15,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 16,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 17,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 18,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 19,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 20,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 21,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 22,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 23,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 24,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
  {
    id: 25,
    title: " Lorem, ipsum dolor.",
    author: "Lorem ipsum",
    img: "",
    text: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam recusandae voluptatum, error saepe illum unde ipsum impedit non quia? Dolorum ut, quod harum quo sint quae aliquam ipsa nemo nihil, eaque officiis dolor commodi magnam inventore reiciendis labore facilis ex impedit at deleniti tempore vel. Natus blanditiis similique, aspernatur, voluptas labore illum nesciunt expedita ad dignissimos, ullam aliquam harum? Sint illum accusantium eius possimus dolores odit? Blanditiis, unde quae! Harum.",
    category: "Fantasy",
  },
];

export default posts;
